name: ebi
description: ebi! is a flutter client for nhentai!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-190.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
